$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        300:{
            items:2
        },
        500:{
            items:3
        },
        700:{
            items:4
        },
        1000:{
            items:5
        }
    }
})
